### ISSUE TITLE
Custom CSS Plugin Rule

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai-plugins#74]
In Custom CSS Plugin Vers. 2.0.1, there is pre-defined rule `remove-colored-dots` which reads
```
/* START [general] remove-color-dots */
span.badge {display:none !important;}
/* END [general] remove-color-dots */
```
When activated, some screens went blank
![image](https://github.com/kevinpapst/kimai-plugins/assets/51003649/179a6d48-3b48-4624-9464-08aefd2dac39)

intended or bug?

**Comment by kevinpapst** [comment]
Hahaha 😁 

I was lazy... try 

```css
.label-activity span.badge, .label-project span.badge, .label-customer span.badge {display:none !important;}
```
